# Generated by Django 4.2.3 on 2023-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_employees_name_employees_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positions",
            name="wage",
            field=models.FloatField(),
        ),
    ]
