# Generated by Django 4.2.3 on 2023-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_positions_wage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animals",
            name="additionalInfo",
            field=models.TextField(max_length=300, null=True),
        ),
    ]
